apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoBinding
metadata:
  name: {{{domainPrefix}}}-binding
  namespace: default
spec:
  description: "{{{domainName}}} binding"
  modelName: {{{domainPrefix}}}-model
  weblogicBindings:
    - name: "{{{domainPrefix}}}"
      replicas: 3
  placement:
    - name: local
      namespaces:
        - name: todo
          components:
            - name: todo
  ingressBindings:
    - name: "{{{domainPrefix}}}-ingress"
      dnsName: "todo.vz.oracledx.com"
  databaseBindings:
{{#databases}}
    - name: "{{{databasePrefix}}}-db"
      url: "{{{url}}}"
      credentials: "{{{databaseCredentials}}}"
{{/databases}}
