# Copyright (c) 2021, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# analytics
googleAnalytics = "UA-129126578-2"

baseURL = "/weblogic-deploy-tooling/"
languageCode = "en-us"
title = "WebLogic Deploy Tooling"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

publishDir = "docs"

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  # disable the copy to clipboard links
  disableInlineCopyToClipBoard = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.superscript]
          enable = true
    [markup.goldmark.renderer]
      # Allow the <sup> tags omitted by the superscript extension.
      unsafe = true
